### ISSUE TITLE
Window on top?

### ISSUE THREAD

**Issue by Miles-Ahead** [zumoshi/BrowserSelect#11]
I noticed that using About in Browser Select window, when clicking the url to come here, Browser Select then opens underneath other windows.  Perhaps an option to use the Topmost attribute would eliminate this?

**Comment by zumoshi** [comment]
Hello,
I just tested this and did not encounter this problem. the new instance of browser select opens on top of the first instance and the about page. however clicking on the about page again causes the first instance to come on top of the new instance (due gaining focus). perhaps that's what happened?

making the browser select window top-most won't solve this issue because both the old instance and the new instance would be top most, therefore it won't help one to come on top of the other one. yet it would make the about window go underneath main window and also won't let you use anything else while browser select is open (since there is no minimize button and it won't go underneath other apps).

but if you tested this again and clicking once on the link in about page, launched browser select under the first instance by default, please provide more information such as os/app version and I'll try to reproduce, perhaps I can add a `this.Activate();` on the main window's load event in case it fails to get focus by default.

**Comment by Miles-Ahead** [comment]
I can no longer reproduce the issue.  Whatever happened it works well now.  :)
