### ISSUE TITLE
VirusTotal indicates presence of virus.win32.sality.at

### ISSUE THREAD

**Issue by JeffGillman** [zumoshi/BrowserSelect#19]
I check everything I download against http://virustotal.com, and the most recent version of BrowserSelect indicates, via scanner Invincea, that virus.win32.sality.at is found within the installer. Info at https://www.virustotal.com/en/file/23c08ac97ab34e4a12d991f06dc0026cddff543d921312ddcf22f03edfccbe44/analysis/1474869235/

**Comment by zumoshi** [comment]
When 56 out of 57 antiviruses detected it as a clean file I would say it's a false positive.

**Comment by JeffGillman** [comment]
I would also consider it a false positive, and would ignore it, especially when I factor in your reputation. But many people do not know your reputation, and don't feel comfortable running anything that gets any hit. I know you can't be responsible for chasing down every false hit, but I mentioned it so that you would know it's happening and that it may be an issue for some. Or maybe there's some easy way to figure out what is triggering the false hit and fixing it. Anyway, thanks for your response. I voted the file Good on VT.

**Comment by zumoshi** [comment]
the last version of BrowserSelect is no longer detected as a virus by `Invincea`.
however, Baidu (which I've never heard of before) has now [decided that it is a virus](https://www.virustotal.com/en/file/2d7d0753dbbd36bf1f355cccd0ecd5cf5fb87b6c5f9b8dcff4682071189fa245/analysis/) ...

looking around [twitter](https://twitter.com/payloadsecurity/status/717821481581953026?lang=en), I don't seem to be the only one affected:
![image](https://cloud.githubusercontent.com/assets/4184939/21256450/a0fbb3a4-c387-11e6-86dd-454918fe0c62.png)

I don't have the time to hunt down after each of these unknown AVs to see why they've decided that BrowserSelect is a virus. generally, i only look at results from reputable AVs (BitDefender, Kaspersky, Comodo, ...). if they think it's safe I don't pay much attention to that one AV that says otherwise.

so, unless you have an idea of how to be more AV friendly, I'm going to close this issue.

**Comment by JeffGillman** [comment]
No ideas here, and I understand the situation.
