### ISSUE TITLE
[feature request] Multiple Monitor Support

### ISSUE THREAD

**Issue by alixandru** [zumoshi/BrowserSelect#22]
Hello,

For multi-monitor setups, it would be nice for the BrowserSelect window to be placed on the monitor on which the source window is displayed.

By source window I mean the the application from which a link was clicked (i.e. an Email client, a PDF viewer, etc).

Thanks!

**Comment by zumoshi** [comment]
hi,

it currently always shows up on the primary monitor. since I personally almost always use the shortcuts instead of clicking on the icons I have not looked at this as a problem, but yeah I guess it could be inconvenient to have to move the mouse to another monitor just to select a browser.

however, I'm not entirely sure how I would detect the source app, since most applications don't execute the browser directly, instead let the windows run the default one, so BrowserSelect's parent is explorer.exe not the real source app. but I guess I can just move it to the display that has the mouse in it.

expect a patch in 48-72 hours.

**Comment by zumoshi** [comment]
I've released a new version (v1.3.6).
can you verify that the issue is fixed in this version?

**Comment by alixandru** [comment]
Thanks for the quick update on this one. The trick you came up with, to use the mouse position, is really awesome - I would have never thought about this.

Unfortunatelly, my corporate antivirus found this release as a threat (WS.Reputation.1) and it won't let me install it, so I cannot test it.

**Comment by alixandru** [comment]
Managed to install and test it. Works like a charm! Thank you!
