### ISSUE TITLE
Opera (blink) doesn't start in Private/Incognito mode

### ISSUE THREAD

**Issue by MailYouLater** [zumoshi/BrowserSelect#35]
Hello again,
Thanks for being so quick with fixing my other issues, and sorry I didn't get this one in before you released 1.3.9 the other day...

BrowserSelect won't launch Opera 52 in private/incognito mode when holding Shift or Alt as it does for the other browsers I've been using.

Apparently Opera doesn't respond to the documented "Unix" and/or "Mac" versions of the "Command Line Options", so what BrowserSelect is currently using (`-newprivatetab`) doesn't work. Unfortunately, the [Opera documentation](https://www.opera.com/docs/switches/) is out of date and doesn't show how to launch it in private mode on Windows. I did some experimenting though, and it does open a new private window when launched with `-private` like this:

    C:\Program Files\Opera\launcher.exe -private http://url.goes/here

I look forward to seeing this fixed in a future version.

**Comment by zumoshi** [comment]
hi,
thanks for your report.

passing `-private` to opera opens the link in a new window, not a new tab (in case there are already other private tabs open).

also, I think pre-blink versions accept the old flag, so changing it would prevent users with an older opera version from opening links in private tabs.

otherwise seems to be an easy fix by changing only a [single line](https://github.com/zumoshi/BrowserSelect/blob/master/BrowserSelect/Browser.cs#L26) of code.

are there any other flags that can open the link in a new tab? or maybe we should try opening an issue on their side for inaccurate documentation to see if they will update the docs or fix the flag so it would work?

**Comment by MailYouLater** [comment]
Any update on what your plans are regarding this issue?

**Comment by zumoshi** [comment]
@MailYouLater sorry for the delay, fixed in v1.4

**Comment by MailYouLater** [comment]
Thanks. Works perfectly.
Sorry I didn't get back to let you know the fix worked earlier. I didn't get notified about the update. I'm submitting a bug report about that.
