### ISSUE TITLE
Specify the same browser with different command lines

### ISSUE THREAD

**Issue by jimdoria** [zumoshi/BrowserSelect#42]
Chrome has the ability to launch different profiles using the command line. Profiles let you separate different logins, bookmarks, etc. for different tasks.

It would be great if you could specify custom browser command lines to launch so that you could launch some sites in one profile, some in another.

**Comment by zumoshi** [comment]
since [v1.4.0](https://github.com/zumoshi/BrowserSelect/releases/tag/1.4.0) browserSelect lists different chrome profiles separately

![](https://user-images.githubusercontent.com/4184939/41280790-13eb49ce-6e45-11e8-9a4b-00ba76f0eda0.png)

do you need to specify command line parameters other than the one for the profile?
also, where do you want to be able to specify this? before clicking on icons when opening an URL? or in the rule list in settings for auto-rules only? or do you want to be able to create new items for the list for browsers with extra command line arguments already specified?

**Comment by jimdoria** [comment]
No, this was what I wanted. I was still on 1.3.9. Thanks for the update!

**Comment by Luckz** [comment]
I want to use different profiles not via Chrome's built in profile system but by specifying --user-data commandline options. I would also like to choose the icon.
