### ISSUE TITLE
Automatic update checker doesn't seem to work.

### ISSUE THREAD

**Issue by MailYouLater** [zumoshi/BrowserSelect#43]
Hi, I was still running an old version for quite a while despite having the "Update checker" option enabled. Upon clicking on the "check now" button, I get a dialog box that says "Unable to check for updates. Please make sure you are connected to internet." but everything else is able to connect to the internet just fine. Is the update checker broken? or is it just on my system?

Either way, please let me know if there's anything I can do to troubleshoot the cause and/or get this working.

![Dialog Box says: Unable to check for updates. Please make sure you are connected to internet.](https://user-images.githubusercontent.com/1279475/43169686-db5945c4-8f56-11e8-9eeb-440aca67be8a.png)

**Comment by zumoshi** [comment]
the problem wasn't on your end, it was broken thanks for your report.

to be more detailed, it seems web request in .net 4 by default uses [sslv3](https://disablessl3.com/), and Github has since I created it disabled that protocol. I patched it to use tls1.2 instead, the patch will be included in the next release.

**Comment by MailYouLater** [comment]
Thanks, I'll try to catch the next update sooner rather than later so that I'll be less likely to miss future updates.
