### ISSUE TITLE
64-bit browsers not listed

### ISSUE THREAD

**Issue by keastin** [zumoshi/BrowserSelect#6]
Hi dev,

In Browser.cs it only looks for browsers at SOFTWARE\Clients\StartMenuInternet.
64-bit browsers are listed in SOFTWARE\WOW6432Node\Clients\StartMenuInternet.
If you add the WOW6432Node key additional browsers could also be found.

**Comment by zumoshi** [comment]
hello,
i dont think that is how it works. 64bit OSes store keys for 32 bit apps in the `WOW6432Node`, just like `program files (x86)` instead of just `program files`.
however when accessing registry with a 32bit program you see the content of `WOW6432Node` when accessing normally.

do you have download link of a 64bit browser that doesnt show up?
i have 64bit firefox developer edition on my system and it shows up on the list.

**Comment by keastin** [comment]
Hi dev,

I probably got it wrong then because I installed Maxthon Cloud Browser and it didn't show up. I guessed it might have something to do with it being a 64-bit browser but I now checked and it wasn't one. I think some browsers are not always listed in either StartMenuInternet location.

After, I manually added Maxthon in the registry and it showed up so I think that's the solution.

Thanks for your help.

**Comment by zumoshi** [comment]
did maxthon browser show up at `Control Panel\Programs\Default Programs\Set Associations` for HTTP protocol before adding it to the registry manually ?
if it did i'll look into it to see where was it listed at instead of `startMenuInternet` key otherwise its a bug on their side , you should file a bug report for them.

**Comment by keastin** [comment]
I looked in `Control Panel\Programs\Default Programs\Set Associations` for the .html file association. I went to `Change program...` and didn't find Maxthon listed in the options. I would have to set the location to it manually there as well.
 It would be a feature request to have adding browsers manually into this program. I could see possibly it would be needed if people used portable web browsers on their computer.
I will most likely file a bug report for Maxthon because I used a non-portable installation.

**Comment by zumoshi** [comment]
since BrowserSelect itself doesn't provide a portable version i don't think adding portable browsers to the list is a very useful feature , what happens if the portable browser was on a usb flash drive and it is removed ?
most mainstream browsers add themselves to the `startMenuInternet` registry key. if they don't its their fault, not BrowserSelects's.

if you really think we need an option to add a browser to the list by using a Browse button in the settings you are welcome to make a pull request but i don't personally consider it useful enough to add such option myself. in fact one of my goals while making browser select as an alternative to [Browser Chooser](http://alternativeto.net/software/browser-chooser/) was to have a Zero-Config plug and play app. one that you install by a few clicks and it just works. having a button to select browsers manually kind of defeats that purpose .

**Comment by keastin** [comment]
I looked at Browser Chooser and it does have the option of adding a browser. That program hasn't been updated in a long time so I'm comfortable with using BrowserSelect.

In the future like you said I can make a pull request to have it added.
