### ISSUE TITLE
Default option

### ISSUE THREAD

**Issue by JeffGillman** [zumoshi/BrowserSelect#8]
For users who mostly want to use one browser, but want to use another one for some sites: I discovered that you can set various filters, and then make the last one just an asterisk as the pattern and select the browser you want to use for everything else, it works fine without the BrowserSelect option dialog popping up. This should either be reflected in the on-screen help for filters, or even better, there could be an option below the filter list: "Open all other sites in [browser picklist]:"

**Comment by zumoshi** [comment]
yes, that works as a side effect of how the pattern matching works, I may add a note on the page to inform users of this behavior. but I don't feel like restructuring the page to add that as a separate option, pull requests are welcome, though.
although since using that option prevents the selecting windows from popping up at all perhaps I should add an option to ask which browser for some patterns (i.e. browser select itself as an option in the drop down). so you can exclude some domains/patterns from the auto select feature.

**Comment by JeffGillman** [comment]
Great idea, adding BrowserSelect itself to the list.

**Comment by zumoshi** [comment]
sorry for the delay I was occupied with some other work, almost done now.
quick question, should `*.google.com` match `google.com` (without subdomain) ?

right now it matches all subdomains of google, but not `google.com` itself, without any subdomains.

**Comment by JeffGillman** [comment]
When I think of the intended use of filters, I would think that *.google.com should match google.com as well. For my simple use, and how I imagine most users would use BrowserSelect, catching the entire domain, subdomains or no, would be the best option.

Thank you.
